project/company_training/urls.py
from django.urls import path

from . import views

app_name = 'company_training'

urlpatterns = [
    path('', views.index, name='index'),
    path('u2g2m/add/', views.add_u2g2m, name='add'),
    path('u2g2m/query/', views.query_u2g2m, name='query'),
    path('u2g2m/<int:id>/edit/', views.edit_u2g2m, name='edit'),
    path('u2g2m/<int:id>/delete/', views.delete_u2g2m, name='delete'),

    path('c2b2t/query/', views.query_c2b2t, name='query_c2b2t'),
    path('test/', views.test, name='test'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # company_training
    path('', include('company_training.urls', namespace='company_training')),
    # users
    path('',include('users.urls', namespace='users')),
    path('users/', include('users.urls', namespace='users')),
]

project/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户登出
    path('/logout/', views.user_logout, name='logout'),
    # 用户信息
    path('  edit/<int:id>/', views.profile_edit, name='edit'),

]

project/company_training/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

# 部门

class Dept(models.Model):
    # 部门id
    dept_id = models.IntegerField(primary_key=True, verbose_name="部门id", null=False, blank=False)
    # 部门名称
    dept_name = models.CharField(max_length=13, verbose_name="部门名称", null=False, blank=False)

    # 内部类 class Meta 用于给 model 定义元数据
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-deptid' 表明数据应该以倒序排列
        ordering = ('dept_id',)
        verbose_name = '部门'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%d: %s' % (self.dept_id, self.dept_name)


# 课程
class Course(models.Model):
    # 课程id
    course_id = models.IntegerField(primary_key=True, verbose_name="课程id", null=False, blank=False)
    # 课程名称
    course_name = models.CharField(max_length=13, verbose_name="课程名称", null=False, blank=False)
    # 课程类别
    course_type = models.CharField(max_length=13, verbose_name="课程类别", null=True, blank=True)

    # 内部类 class Meta 用于给 model 定义元数据
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-deptid' 表明数据应该以倒序排列
        ordering = ('course_id',)
        verbose_name = '课程'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%d: %s' % (self.course_id, self.course_name)


# 教材
class Book(models.Model):
    # 教材id
    book_id = models.IntegerField(primary_key=True, verbose_name="教材id", null=False, blank=False)
    # 教材名称
    book_name = models.CharField(max_length=13, verbose_name="教材名称", null=False, blank=False)
    # 教材价格
    book_price = models.DecimalField(verbose_name="教材价格", max_digits=8,
                                     decimal_places=2, null=True, blank=True)
    book_pubtdate = models.DateField()

    # 内部类 class Meta 用于给 model 定义元数据
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-deptid' 表明数据应该以倒序排列
        ordering = ('book_id',)
        verbose_name = '教材'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%d: %s' % (self.book_id, self.book_name)


# 讲师
class Teacher(models.Model):
    # 讲师id
    teacher_id = models.IntegerField(primary_key=True, verbose_name="讲师id", null=False, blank=False)
    # 讲师名称
    teacher_name = models.CharField(max_length=13, verbose_name="讲师姓名", null=False, blank=False)
    # 讲师性别
    gender = models.CharField(max_length=8, choices=(('male', '男'), ('female', '女')), verbose_name="讲师性别", null=True,
                              blank=True)
    # 年龄
    age = models.IntegerField(verbose_name="年龄", null=True, blank=True)
    # 学历
    education = models.CharField(max_length=12, choices=(('high school', '高中'), ('bachelor', '本科'),
                                                         ('postgraduate', '研究生'), ('doctor', '博士')),
                                 verbose_name="学历", null=True, blank=True)
    # 电话号码字段
    phone = models.CharField(max_length=20, blank=True)
    # 个人简介
    bio = models.TextField(max_length=500, blank=True)
    # 是否是外聘
    is_external = models.BooleanField(default=False, verbose_name="是否是外聘")

    # 内部类 class Meta 用于给 model 定义元数据
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-deptid' 表明数据应该以倒序排列
        ordering = ('teacher_id',)
        verbose_name = '讲师'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%d: %s' % (self.teacher_id, self.teacher_name)


# 课程-教材-讲师
class C2B2T(models.Model):
    # 序列id
    c2b2t_id = models.IntegerField(primary_key=True, verbose_name="序列id", null=False, blank=False)
    # 课程id
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    # 讲师id
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    # 教材id
    book = models.ForeignKey(Book, on_delete=models.DO_NOTHING)
    # 开课时间
    begin_time = models.DateField()
    # 学时（h）
    period = models.IntegerField(verbose_name="学时(h)", null=False, blank=False)

    # 内部类 class Meta 用于给 model 定义元数据
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-deptid' 表明数据应该以倒序排列
        ordering = ('-c2b2t_id',)
        verbose_name = '课程_教材_讲师'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%d' % self.c2b2t_id


# 员工-课程序列
class U2G2M(models.Model):
    # 员工id
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # 序列id
    c2b2t = models.ForeignKey(C2B2T, on_delete=models.CASCADE)
    # 成绩
    grade = models.IntegerField(verbose_name="成绩", default=0)

    class Meta:
        unique_together = ("user", "c2b2t")
        ordering = ('-c2b2t',)
        verbose_name = '员工_课程序列'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%d %d' % (self.user.id, self.c2b2t.c2b2t_id)

project/company_training/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from .models import U2G2M, C2B2T, Course, Teacher
from django.contrib.auth.models import User
from users.models import Profile
from django.db.models import F, Q


# Create your views here.

def index(request):
    profile = Profile.objects.get(user=request.user)
    return render(request, 'company_training/index.html', context={
        'title': '公司培训系统首页',
        'welcome': '欢迎访问公司培训系统首页',
        'profile': profile,
    })


# 增加学员课程 u2g2m
@csrf_exempt
# @login_required(login_url='/users/login/')
def add_u2g2m(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == "POST":
        c2b2t_id = request.POST.get("c2b2t")
        user_id = request.POST.get("user")
        user = User.objects.get(id=user_id)
        c2b2t = C2B2T.objects.get(c2b2t_id=c2b2t_id)
        U2G2M.objects.create(user=user, c2b2t=c2b2t, grade=0)

        return HttpResponse("success")

    c2b2t_list = C2B2T.objects.all()
    user_list = User.objects.all()
    return render(request, "company_training/add_u2g2m.html",
                  {'title': '员工选课', 'topic': '为员工增加课程',
                   "c2b2t_list": c2b2t_list,
                   "user_list": user_list,
                   'profile': profile,
                   })


@csrf_exempt
def query_u2g2m(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == "GET":
        if not profile.is_manager:
            # 员工查询
            ret_list = U2G2M.objects.filter(user=request.user).values("id",
                                                                      "c2b2t__c2b2t_id",
                                                                      "c2b2t__course__course_name",
                                                                      "user__id",
                                                                      "user__profile__name",
                                                                      "grade")
            context = {"ret_list": ret_list, 'topic': '查看我的课程成绩', 'title': '查看成绩',
                       'profile': profile}
            return render(request, "company_training/query_u2g2m.html",
                          context=context)
        else:
            # 经理查询
            # 未查询默认显示全部成绩结果

            # 获取表中的可选值
            c2b2t_list = C2B2T.objects.all()
            course_list = Course.objects.all()
            u2g2m_list = U2G2M.objects.all()
            profile_list = Profile.objects.all()

            # 显示查询结果
            ret_list = U2G2M.objects.all().values("id",
                                                  "c2b2t__c2b2t_id",
                                                  "c2b2t__course__course_name",
                                                  "user__id",
                                                  "user__profile__name",
                                                  "grade")
            context = {"ret_list": ret_list,
                       'topic': '查看员工课程成绩',
                       'title': '查看成绩',
                       "c2b2t_list": c2b2t_list,
                       "course_list": course_list,
                       "u2g2m_list": u2g2m_list,
                       "profile_list": profile_list,
                       'profile': profile,
                       }
            return render(request, "company_training/query_u2g2m.html",
                          context=context)

    else:
        if not profile.is_manager:
            return HttpResponse("只有经理才能查询所有人成绩")
        else:
            # 经理查询
            # 多条件查询
            c2b2t_id = request.POST.get("c2b2t_id")
            cname = request.POST.get("cname")
            userid = request.POST.get("userid")

            con = Q()
            q1 = Q()
            q1.connector = 'AND'  # q1对象表示‘AND’关系，也就是说q1下的条件都要满足‘AND’

            q2 = Q()
            q2.connector = 'OR'
            # 判断前台传过来的值是否存在，存在的话追加到去Q对象中，不存在的话可以赋一个空值
            if c2b2t_id:
                q1.children.append(('c2b2t__c2b2t_id', c2b2t_id))
            else:
                pass

            # cname
            if cname:
                q1.children.append(('c2b2t__course__course_name', cname))
            else:
                pass

            # userid
            if userid:
                q1.children.append(('user__id', int(userid)))
            else:
                pass

            # 把q1和q2对象添加到总的Q对象
            con.add(q1, 'AND')
            con.add(q2, 'AND')

            c2b2t_list = C2B2T.objects.all()
            course_list = Course.objects.all()
            u2g2m_list = U2G2M.objects.all()
            profile_list = Profile.objects.all()

            # 显示查询结果
            ret_list = U2G2M.objects.filter(con).values("id",
                                                        "c2b2t__c2b2t_id",
                                                        "c2b2t__course__course_name",
                                                        "user__id",
                                                        "user__profile__name",
                                                        "grade")
            context = {"ret_list": ret_list,
                       'topic': '查看员工课程成绩',
                       'title': '查看成绩',
                       "c2b2t_list": c2b2t_list,
                       "course_list": course_list,
                       "u2g2m_list": u2g2m_list,
                       "profile_list": profile_list,
                       'c2b2t_id': c2b2t_id,
                       'cname': cname,
                       'userid': userid,
                       'profile': profile,
                       }

            return render(request, "company_training/query_u2g2m.html",
                          context=context)


def query_c2b2t(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == "GET":
        if not profile.is_manager:
            # 员工查询
            ret_list = U2G2M.objects.filter(user=request.user).values("id",
                                                                      "c2b2t__c2b2t_id",  # 课程序列
                                                                      "c2b2t__course__course_name",  # 课程名称
                                                                      "user__id",  # 员工id
                                                                      "user__profile__name",  # 员工姓名
                                                                      "c2b2t__teacher__teacher_name",  # 讲师姓名
                                                                      "c2b2t__begin_time",  # 课程开始时间
                                                                      "c2b2t__period",  # 学时
                                                                      )
            context = {"ret_list": ret_list, 'topic': '查看我的课程', 'title': '查看课表',
                       'profile': profile}
            return render(request, "company_training/query_c2b2t.html",
                          context=context)
        else:
            # 经理查询
            # 未查询默认显示全部成绩结果

            # 获取表中的可选值
            c2b2t_list = C2B2T.objects.all()  # 课程序号查询
            course_list = Course.objects.all()  # 课程名称查询
            u2g2m_list = U2G2M.objects.all()  #
            profile_list = Profile.objects.all()  # 员工姓名查询
            teacher_list = Teacher.objects.all()  # 讲师姓名查询

            # 显示查询结果
            ret_list = U2G2M.objects.filter(user=request.user).values("id",
                                                                      "c2b2t__c2b2t_id",  # 课程序列
                                                                      "c2b2t__course__course_name",  # 课程名称
                                                                      "user__id",  # 员工id
                                                                      "user__profile__name",  # 员工姓名
                                                                      "c2b2t__teacher__teacher_name",  # 讲师姓名
                                                                      "c2b2t__begin_time",  # 课程开始时间
                                                                      "c2b2t__period",  # 学时
                                                                      )
            context = {"ret_list": ret_list,
                       'topic': '查看员工课程',
                       'title': '查看课程',
                       "c2b2t_list": c2b2t_list,
                       "course_list": course_list,
                       "u2g2m_list": u2g2m_list,
                       "profile_list": profile_list,
                       'profile': profile,
                       'teacher_list': teacher_list,
                       }
            return render(request, "company_training/query_c2b2t.html",
                          context=context)

    else:
        if not profile.is_manager:
            return HttpResponse("只有经理才能查询所有人课程")
        else:
            # 经理查询
            # 多条件查询
            c2b2t_id = request.POST.get("c2b2t_id")
            cname = request.POST.get("cname")
            userid = request.POST.get("userid")
            tname = request.POST.get("tname")

            con = Q()
            q1 = Q()
            q1.connector = 'AND'  # q1对象表示‘AND’关系，也就是说q1下的条件都要满足‘AND’

            q2 = Q()
            q2.connector = 'OR'
            # 判断前台传过来的值是否存在，存在的话追加到去Q对象中，不存在的话可以赋一个空值
            if c2b2t_id:
                q1.children.append(('c2b2t__c2b2t_id', c2b2t_id))
            else:
                pass

            # cname
            if cname:
                q1.children.append(('c2b2t__course__course_name', cname))
            else:
                pass

            # userid
            if userid:
                q1.children.append(('user__id', int(userid)))
            else:
                pass
            # tname
            if tname:

project/templates/company_training/add_u2g2m.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    增加学员课程
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<div class="col-md-4">{{ topic }}</div>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="." method="post">
                {% csrf_token %}
                <div class="form-group">
                    <lable for="">课程序列</lable>
                    <select name="c2b2t" id="c2b2t" class="form-control">
                        {% for c2b2t in c2b2t_list %}
                        <option value="{{c2b2t.c2b2t_id}}">{{c2b2t.c2b2t_id}}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <lable for="">员工</lable>
                    <select name="user" id="user" class="form-control">
                        {% for user in user_list %}
                        <option value="{{user.id}}">{{user.id}}:{{user.username}}</option>
                        {% endfor %}
                    </select>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
           </form>
        </div>
    </div>
</div>


{% endblock content %}

project/templates/company_training/edit_u2g2m.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    更改学员成绩
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<div class="col-md-4">{{ topic }}</div>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="col-md-4">课程序列 : {{ edit_u2g2m.c2b2t.c2b2t_id }}</div>
            <div class="col-md-4">用户 : {{ edit_u2g2m.user.username }}</div>
            <form action="." method="post">
                {% csrf_token %}
                <div class="form-group col-md-4">
                    <label for="grade">成绩</label>
                    <input type="number" class="form-control" id="grade" name="grade"
                           placeholder="0~100" value="{{ edit_u2g2m.grade }}" min="0" max="100">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
           </form>
        </div>
    </div>
</div>


{% endblock content %}

project/templates/company_training/index.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    {{ title }}
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
{{ welcome }}
<!-- 定义放置文章标题的div容器 -->


<div class="container">
    <div class="row mt-2">

    </div>
</div>
{% endblock content %}

project/templates/company_training/query_c2b2t.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    查看学员课程
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<div class="col-md-4">{{ topic }}</div>

{% if profile.is_manager %}
<div class="container">
    <div class="row">
        <div class="col-md-12 col-md-offset-3">
            <form action="." method="post">
                <div class="form-row">
                    {% csrf_token %}
                    <div class="col">
                        <lable for="">员工id</lable>
    <!--                    <input type="number" name="userid" class="form-control"-->
    <!--                            value="{{ userid }}" min="0">-->
                        <input type="text" name="userid" class="form-control"
                                value="{{ userid }}">
                    </div>
<!--                    <div class="form-group">-->
                    <div class="col">
                        <lable for="">课程名称</lable>
                        <select name="cname" id="cname" class="form-control">
                            <option selected value=""></option>
                            {% for course in course_list %}
                                {% if course.course_name == cname %}
                                <option selected value="{{course.course_name}}">{{course.course_name}}</option>
                                {% else %}
                                <option value="{{course.course_name}}">{{course.course_name}}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>

                     <div class="form-group col-md-12">
                        <lable for="">课程序号</lable>
                        <select name="c2b2t_id" id="c2b2t_id" class="form-control">
                            <option selected value=""></option>
                            {% for c2b2t in c2b2t_list %}
                                {% if c2b2t.c2b2t_id == c2b2t_id %}
                                <option selected value="{{c2b2t.c2b2t_id}}">{{c2b2t.c2b2t_id}}</option>
                                {% else %}
                                <option value="{{c2b2t.c2b2t_id}}">{{c2b2t.c2b2t_id}}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                  <div class="form-group col-md-12">
                        <lable for="">讲师姓名</lable>
                        <select name="tname" id="tname" class="form-control">
                            <option selected value=""></option>
                            {% for teacher in teacher_list %}
                                {% if teacher.teacher_name == tname %}
                                <option selected value="{{teacher.teacher_name}}">{{teacher.teacher_name}}</option>
                                {% else %}
                                <option value="{{teacher.teacher_name}}">{{teacher.teacher_name}}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <div>
                    <button type="submit" class="btn btn-primary">查询</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endif %}


<div class="container mt-2">
    <div class="row">
        <div class="col-md-12 col-md-offset-3">
          <!--            <a href="/books/add/" class="btn btn-primary">添加书籍</a>-->
        <table class="table table-bordered table-hover table-striped">
            <thead>
                    <tr>
                         <th>序号</th>
                         <th>课程编号</th>
                         <th>课程名称</th>
                         <th>员工编号</th>
                         <th>员工姓名</th>
                         <th>讲师</th>
                         <th>开课时间</th>
                         <th>学时(h)</th>

                        {% if profile.is_manager %}
                         <th>操作</th>
                        {% endif %}
                    </tr>
                 </thead>
            <tbody>
                      {% for ret in ret_list %}
                      <tr>
                           <td>{{ forloop.counter }}</td>
                           <td>{{ ret.c2b2t__c2b2t_id }}</td>
                           <td>{{ ret.c2b2t__course__course_name }}</td>
                           <td>{{ ret.user__id }}</td>
                           <td>{{ ret.user__profile__name }}</td>
                           <td>{{ ret.c2b2t__teacher__teacher_name }}</td>
                           <td>{{ ret.c2b2t__begin_time }}</td>
                           <td>{{ ret.c2b2t__period }}</td>

                            {% if profile.is_manager %}
                           <td>
                               <a href="{% url 'company_training:delete' id=ret.id%}" class="btn btn-danger">删除</a>
                           </td>
                            {% endif %}

                      </tr>
                      {% endfor %}

                 </tbody>
        </table>
        </div>
    </div>
</div>


{% endblock content %}

project/templates/company_training/query_u2g2m.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    查看学员课程成绩
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<div class="col-md-4">{{ topic }}</div>

{% if profile.is_manager %}
<div class="container">
    <div class="row">
        <div class="col-md-12 col-md-offset-3">
            <form action="." method="post">
                <div class="form-row">
                    {% csrf_token %}
                    <div class="col">
                        <lable for="">员工id</lable>
    <!--                    <input type="number" name="userid" class="form-control"-->
    <!--                            value="{{ userid }}" min="0">-->
                        <input type="text" name="userid" class="form-control"
                                value="{{ userid }}">
                    </div>
<!--                    <div class="form-group">-->
                    <div class="col">
                        <lable for="">课程名称</lable>
                        <select name="cname" id="cname" class="form-control">
                            <option selected value=""></option>
                            {% for course in course_list %}
                                {% if course.course_name == cname %}
                                <option selected value="{{course.course_name}}">{{course.course_name}}</option>
                                {% else %}
                                <option value="{{course.course_name}}">{{course.course_name}}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>

                     <div class="form-group col-md-12">
                        <lable for="">课程序号</lable>
                        <select name="c2b2t_id" id="c2b2t_id" class="form-control">
                            <option selected value=""></option>
                            {% for c2b2t in c2b2t_list %}
                                {% if c2b2t.c2b2t_id == c2b2t_id %}
                                <option selected value="{{c2b2t.c2b2t_id}}">{{c2b2t.c2b2t_id}}</option>
                                {% else %}
                                <option value="{{c2b2t.c2b2t_id}}">{{c2b2t.c2b2t_id}}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <div>
                    <button type="submit" class="btn btn-primary">查询</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endif %}


<div class="container mt-2">
    <div class="row">
        <div class="col-md-12 col-md-offset-3">
          <!--            <a href="/books/add/" class="btn btn-primary">添加书籍</a>-->
        <table class="table table-bordered table-hover table-striped">
            <thead>
                    <tr>
                         <th>序号</th>
                         <th>课程编号</th>
                         <th>课程名称</th>
                         <th>员工编号</th>
                         <th>员工姓名</th>
                         <th>成绩</th>
                        {% if profile.is_manager %}
                         <th>操作</th>
                        {% endif %}
                    </tr>
                 </thead>
            <tbody>
                      {% for ret in ret_list %}
                      <tr>
                           <td>{{ forloop.counter }}</td>
                           <td>{{ ret.c2b2t__c2b2t_id }}</td>
                           <td>{{ ret.c2b2t__course__course_name }}</td>
                           <td>{{ ret.user__id }}</td>
                           <td>{{ ret.user__profile__name }}</td>
                           <td>{{ ret.grade }}</td>
                            {% if profile.is_manager %}
                           <td>
                               <a href="{% url 'company_training:edit' id=ret.id%}" class="btn btn-warning">编辑</a>
                               <a href="{% url 'company_training:delete' id=ret.id%}" class="btn btn-danger">删除</a>
                           </td>
                            {% endif %}

                      </tr>
                      {% endfor %}

                 </tbody>
        </table>
        </div>
    </div>
</div>


{% endblock content %}