project/company_training/urls.py
from django.urls import path

from . import views

app_name = 'company_training'

urlpatterns = [
    path('', views.index, name='index'),
    path('u2g2m/add/', views.add_u2g2m, name='add'),
    path('u2g2m/query/', views.query_u2g2m, name='query'),
    path('u2g2m/<int:id>/edit/', views.edit_u2g2m, name='edit'),
    path('u2g2m/<int:id>/delete/', views.delete_u2g2m, name='delete'),

    path('c2b2t/query/', views.query_c2b2t, name='query_c2b2t'),
    path('test/', views.test, name='test'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # company_training
    path('', include('company_training.urls', namespace='company_training')),
    # users
    path('',include('users.urls', namespace='users')),
    path('users/', include('users.urls', namespace='users')),
]

project/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户登出
    path('/logout/', views.user_logout, name='logout'),
    # 用户信息
    path('  edit/<int:id>/', views.profile_edit, name='edit'),

]

project/templates/base.html
<!--
    载入静态文件
    使用 Django 3 学习的读者改为 {% load static %}
-->
{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
     <link rel="stylesheet" href="{% static 'bootstrap/css/w3.css' %}">
      <style>
        .navbar {
            margin-bottom: 0;
            position: fixed;
            left: 0;
            right: 0;
        }

        .sidebar {
            background: lightgray;
            padding: 0;
            position: fixed;
            top: 52px;
            bottom: 0;
        }

        .content {
            position: fixed;
            top: 52px;
            right: 0;
            bottom: 40px;
            overflow: scroll;
        }
    </style>

</head>
<body>
    <!-- 引入导航栏 -->
    <div class="navbar navbar-inverse"></div>

        {% include 'header.html' %}


        <div class="container-fluid main">
        <div class="row">
            <div class="col-md-2 sidebar">
                <nav class="w3-sidenav w3-dark-grey">
                    {% if profile.is_manager%}
                     <a href="{% url 'company_training:add' %}">增加员工课程</a>
                    {% endif %}
                        <a href="{% url 'company_training:query' %}">查看课程成绩</a>
                        <a href="{% url 'company_training:query_c2b2t' %}">查看课程表</a>
            <!--      <div class="w3-dropdown-hover">-->
            <!--        <a href="#">Dropdown <i class="fa fa-caret-down"></i></a>-->
            <!--        <div class="w3-dropdown-content w3-white w3-card-4">-->
            <!--          <a href="#">Link 1</a>-->
            <!--          <a href="#">Link 2</a>-->
            <!--          <a href="#">Link 3</a>-->
            <!--        </div>-->
                </nav>
            </div>
            <div class="col-md-10 content pull-right">
                <!-- 预留具体页面的位置 -->
                {% block content %}{% endblock content %}

            </div>
        </div>
    </div>









    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>

    <!--
        popper.js 采用 cdn 远程引入，意思是你不需要把它下载到本地。
        在实际的开发中推荐静态文件尽量都使用 cdn 的形式。
        教程采用本地引入是为了让读者了解静态文件本地部署的流程。
    -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>

    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

project/templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; cyf....</p>
    </div>
</footer>

project/templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">

    <!-- 导航栏商标 -->
    <a class="navbar-brand" href="{% url 'company_training:index' %}">公司培训系统</a>

    <!-- 导航入口 -->
    <div>
      <ul class="navbar-nav">
        <!-- 条目 -->
      {% if user.is_authenticated %}
        <!-- 如果用户已经登录，则显示用户名下拉框 -->
        <li class="nav-item">
          <a class="nav-link" href="#">通知</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:edit' user.id %}">个人信息</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">退出登录</a>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
<!--                <a class="dropdown-item" href="{% url 'users:edit' user.id %}">个人信息</a>-->
<!--                <a class="dropdown-item" href="{% url 'users:logout' %}">退出登录</a>-->
            </div>
        </li>
    <!-- 如果用户未登录，则显示 “登录” -->
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">登录</a>
        </li>
    <!-- if 语句在这里结束 -->
    {% endif %}
      </ul>
    </div>

  </div>
</nav>